#!/usr/bin/env python3
"""
Extract BYE positions per N from personaladmin/CHAVES CT.xlsx.

For N=6..22: reads the explicit 'isbye' column from the SQL-friendly table on
each sheet.

For N=2..5 and N=23..77: uses derived formula
  byes_count = min(N - pow2_below, pow2_above - N)
with standard tournament seeding positions (1, N, N/2+1, N/2, ...). These rows
are commented as DERIVED in the output SQL so a human can verify against the
spreadsheet.

Generates backend/prisma/seeds/bracket_chaves_byes.sql.

Usage:
  cd backend && python scripts/extract-bracket-byes.py
"""
from openpyxl import load_workbook
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / 'personaladmin' / 'CHAVES CT.xlsx'
OUT  = ROOT / 'backend' / 'prisma' / 'seeds' / 'bracket_chaves_byes.sql'

def pow2_below(n: int) -> int:
    return 1 << (n.bit_length() - 1) if n > 0 else 0

def pow2_above(n: int) -> int:
    return 1 << n.bit_length() if (n & (n - 1)) else n

def derived_byes(n: int) -> list[int]:
    """Fallback for sheets without explicit table. Standard seeding."""
    pb, pa = pow2_below(n), pow2_above(n)
    count = min(n - pb, pa - n)
    if count == 0: return []
    # Top seeds for a tournament of size N: 1, N, N/2+1, N/2, N/4+1, ...
    # We pick the first `count` seeds and sort by position.
    seeds = [1, n]
    if count > 2:
        mid_top = (n // 2) + 1
        mid_bot = n // 2
        seeds.extend([mid_top, mid_bot])
    if count > 4:
        # Recurse: split halves
        for q in [n // 4 + 1, n // 4, n * 3 // 4 + 1, n * 3 // 4]:
            if 1 <= q <= n and q not in seeds: seeds.append(q)
    return sorted(seeds[:count])

def explicit_byes(ws, n: int) -> list[int] | None:
    """Read the 'isbye' column from the sheet's SQL table if present."""
    header_row = start_col = None
    for r in range(1, ws.max_row + 1):
        for c in range(1, ws.max_column + 1):
            if ws.cell(row=r, column=c).value == 'Chave':
                header_row, start_col = r, c
                break
        if header_row: break
    if not header_row: return None
    byes = []
    for r in range(header_row + 1, header_row + 1 + n):
        pos = ws.cell(row=r, column=start_col + 1).value
        isbye = ws.cell(row=r, column=start_col + 6).value
        if (isinstance(isbye, bool) and isbye) or str(isbye).lower() == 'true':
            byes.append(pos)
    return sorted(byes)

def main():
    wb = load_workbook(XLSX, data_only=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        '-- Auto-generated by backend/scripts/extract-bracket-byes.py',
        '-- DO NOT EDIT MANUALLY. To regenerate: cd backend && python scripts/extract-bracket-byes.py',
        '',
    ]

    for n in range(2, 78):
        sn = f'{n:02d}'
        if sn not in wb.sheetnames: continue
        ws = wb[sn]
        explicit = explicit_byes(ws, n)
        if explicit is not None:
            byes = explicit
            source = 'EXPLICIT (planilha tem tabela isbye)'
        else:
            byes = derived_byes(n)
            source = 'DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR'
        arr = '{' + ','.join(str(b) for b in byes) + '}'
        lines.append(f"-- N={n}: {source}")
        lines.append(
            f"INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) "
            f"VALUES ({n}, '{arr}') "
            f"ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;"
        )
        lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT} ({len(lines)} lines)')

if __name__ == '__main__':
    main()
