-- Auto-generated by backend/scripts/extract-bracket-graphs.py
-- DO NOT EDIT MANUALLY. To regenerate: cd backend && python scripts/extract-bracket-graphs.py

-- N=2: PENDING (visual parser not yet implemented; will add in task 3)

-- N=3: PENDING (visual parser not yet implemented; will add in task 3)

-- N=4: PENDING (visual parser not yet implemented; will add in task 3)

-- N=5: PENDING (visual parser not yet implemented; will add in task 3)

-- N=6: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (6, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P4","bottom":"P5","round":1},{"id":"J3","top":"P1","bottom":"V:J1","round":2},{"id":"J4","top":"V:J2","bottom":"P6","round":2},{"id":"J5","top":"L:J3","bottom":"L:J4","round":3},{"id":"J6","top":"V:J3","bottom":"V:J4","round":3}],"final":"J6","thirdPlace":"J5"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=7: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (7, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P4","bottom":"P5","round":1},{"id":"J3","top":"P6","bottom":"P7","round":1},{"id":"J4","top":"P1","bottom":"V:J1","round":2},{"id":"J5","top":"V:J2","bottom":"V:J3","round":2},{"id":"J6","top":"L:J4","bottom":"L:J5","round":3},{"id":"J7","top":"V:J4","bottom":"V:J5","round":3}],"final":"J7","thirdPlace":"J6"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=8: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (8, '{"matches":[{"id":"J1","top":"P1","bottom":"P2","round":1},{"id":"J2","top":"P3","bottom":"P4","round":1},{"id":"J3","top":"P5","bottom":"P6","round":1},{"id":"J4","top":"P7","bottom":"P8","round":1},{"id":"J5","top":"V:J1","bottom":"V:J2","round":2},{"id":"J6","top":"V:J3","bottom":"V:J4","round":2},{"id":"J7","top":"L:J5","bottom":"L:J6","round":3},{"id":"J8","top":"V:J5","bottom":"V:J6","round":3}],"final":"J8","thirdPlace":"J7"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=9: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (9, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P1","bottom":"V:J1","round":2},{"id":"J3","top":"P4","bottom":"P5","round":1},{"id":"J4","top":"P6","bottom":"P7","round":1},{"id":"J5","top":"P8","bottom":"P9","round":1},{"id":"J6","top":"V:J2","bottom":"V:J3","round":3},{"id":"J7","top":"V:J4","bottom":"V:J5","round":2},{"id":"J8","top":"L:J6","bottom":"L:J7","round":4},{"id":"J9","top":"V:J6","bottom":"V:J7","round":4}],"final":"J9","thirdPlace":"J8"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=10: PENDING (visual parser not yet implemented; will add in task 3)

-- N=11: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (11, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P7","bottom":"P8","round":1},{"id":"J3","top":"P9","bottom":"P10","round":1},{"id":"J4","top":"P1","bottom":"V:J1","round":2},{"id":"J5","top":"P4","bottom":"P5","round":1},{"id":"J6","top":"P6","bottom":"V:J2","round":2},{"id":"J7","top":"V:J3","bottom":"P11","round":2},{"id":"J8","top":"V:J4","bottom":"V:J5","round":3},{"id":"J9","top":"V:J6","bottom":"V:J7","round":3},{"id":"J10","top":"L:J8","bottom":"L:J9","round":4},{"id":"J11","top":"V:J8","bottom":"V:J9","round":4}],"final":"J11","thirdPlace":"J10"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=12: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (12, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P4","bottom":"P5","round":1},{"id":"J3","top":"P8","bottom":"P9","round":1},{"id":"J4","top":"P10","bottom":"P11","round":1},{"id":"J5","top":"P1","bottom":"V:J1","round":2},{"id":"J6","top":"V:J2","bottom":"P6","round":2},{"id":"J7","top":"P7","bottom":"V:J3","round":2},{"id":"J8","top":"V:J4","bottom":"P12","round":2},{"id":"J9","top":"V:J5","bottom":"V:J6","round":3},{"id":"J10","top":"V:J7","bottom":"V:J8","round":3},{"id":"J11","top":"L:J9","bottom":"L:J10","round":4},{"id":"J12","top":"V:J9","bottom":"V:J10","round":4}],"final":"J12","thirdPlace":"J11"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=13: PENDING (visual parser not yet implemented; will add in task 3)

-- N=14: PENDING (visual parser not yet implemented; will add in task 3)

-- N=15: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (15, '{"matches":[{"id":"J15","top":"V:J12","bottom":"V:J13","round":4},{"id":"J14","top":"L:J12","bottom":"L:J13","round":4},{"id":"J13","top":"V:J10","bottom":"V:J11","round":3},{"id":"J12","top":"V:J8","bottom":"V:J9","round":3},{"id":"J11","top":"V:J6","bottom":"V:J7","round":2},{"id":"J10","top":"V:J4","bottom":"V:J5","round":2},{"id":"J9","top":"V:J2","bottom":"V:J3","round":2},{"id":"J8","top":"P1","bottom":"V:J1","round":2},{"id":"J7","top":"P14","bottom":"P15","round":1},{"id":"J6","top":"P12","bottom":"P13","round":1},{"id":"J5","top":"P10","bottom":"P11","round":1},{"id":"J4","top":"P8","bottom":"P9","round":1},{"id":"J3","top":"P6","bottom":"P7","round":1},{"id":"J2","top":"P4","bottom":"P5","round":1},{"id":"J1","top":"P2","bottom":"P3","round":1}],"final":"J15","thirdPlace":"J14"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=16: PENDING (visual parser not yet implemented; will add in task 3)

-- N=17: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (17, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P1","bottom":"V:J1","round":2},{"id":"J3","top":"P4","bottom":"P5","round":1},{"id":"J4","top":"P6","bottom":"P7","round":1},{"id":"J5","top":"P8","bottom":"P9","round":1},{"id":"J6","top":"P10","bottom":"P11","round":1},{"id":"J7","top":"P12","bottom":"P13","round":1},{"id":"J8","top":"P14","bottom":"P15","round":1},{"id":"J9","top":"P16","bottom":"P17","round":1},{"id":"J10","top":"V:J2","bottom":"V:J3","round":3},{"id":"J11","top":"V:J4","bottom":"V:J5","round":2},{"id":"J12","top":"V:J6","bottom":"V:J7","round":2},{"id":"J13","top":"V:J8","bottom":"V:J9","round":2},{"id":"J14","top":"V:J10","bottom":"V:J11","round":4},{"id":"J15","top":"V:J12","bottom":"V:J13","round":3},{"id":"J16","top":"L:J14","bottom":"L:J15","round":5},{"id":"J17","top":"V:J14","bottom":"V:J15","round":5}],"final":"J17","thirdPlace":"J16"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=18: PENDING (visual parser not yet implemented; will add in task 3)

-- N=19: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (19, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P11","bottom":"P12","round":1},{"id":"J3","top":"P17","bottom":"P18","round":1},{"id":"J4","top":"P1","bottom":"V:J1","round":2},{"id":"J5","top":"P4","bottom":"P5","round":1},{"id":"J6","top":"P6","bottom":"P7","round":1},{"id":"J7","top":"P8","bottom":"P9","round":1},{"id":"J8","top":"P10","bottom":"V:J2","round":2},{"id":"J9","top":"P13","bottom":"P14","round":1},{"id":"J10","top":"P15","bottom":"P16","round":1},{"id":"J11","top":"V:J3","bottom":"P19","round":2},{"id":"J12","top":"V:J4","bottom":"V:J5","round":3},{"id":"J13","top":"V:J6","bottom":"V:J7","round":2},{"id":"J14","top":"V:J8","bottom":"V:J9","round":3},{"id":"J15","top":"V:J10","bottom":"V:J11","round":3},{"id":"J16","top":"V:J12","bottom":"V:J13","round":4},{"id":"J17","top":"V:J14","bottom":"V:J15","round":4},{"id":"J18","top":"L:J16","bottom":"L:J17","round":5},{"id":"J19","top":"P19","bottom":"P2","round":1}],"final":"J16","thirdPlace":"J18"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=20: PENDING (visual parser not yet implemented; will add in task 3)

-- N=21: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (21, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P8","bottom":"P9","round":1},{"id":"J3","top":"P12","bottom":"P13","round":1},{"id":"J4","top":"P17","bottom":"P18","round":1},{"id":"J5","top":"P19","bottom":"P20","round":1},{"id":"J6","top":"P1","bottom":"V:J1","round":2},{"id":"J7","top":"P4","bottom":"P5","round":1},{"id":"J8","top":"P6","bottom":"P7","round":1},{"id":"J9","top":"V:J2","bottom":"P10","round":2},{"id":"J10","top":"P11","bottom":"V:J3","round":2},{"id":"J11","top":"P14","bottom":"P15","round":1},{"id":"J12","top":"P16","bottom":"V:J4","round":2},{"id":"J13","top":"V:J5","bottom":"P21","round":2},{"id":"J14","top":"V:J6","bottom":"V:J7","round":3},{"id":"J15","top":"V:J8","bottom":"V:J9","round":3},{"id":"J16","top":"V:J10","bottom":"V:J11","round":3},{"id":"J17","top":"V:J12","bottom":"V:J13","round":3},{"id":"J18","top":"V:J14","bottom":"V:J15","round":4},{"id":"J19","top":"V:J16","bottom":"V:J17","round":4},{"id":"J20","top":"L:J18","bottom":"L:J19","round":5},{"id":"J21","top":"P21","bottom":"P2","round":1}],"final":"J18","thirdPlace":"J20"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=22: EXPLICIT
INSERT INTO bracket_chaves_matches (numero_inscrito, matches_graph) VALUES (22, '{"matches":[{"id":"J1","top":"P2","bottom":"P3","round":1},{"id":"J2","top":"P7","bottom":"P8","round":1},{"id":"J3","top":"P9","bottom":"P10","round":1},{"id":"J4","top":"P13","bottom":"P14","round":1},{"id":"J5","top":"P18","bottom":"P19","round":1},{"id":"J6","top":"P20","bottom":"P21","round":1},{"id":"J7","top":"P1","bottom":"V:J1","round":2},{"id":"J8","top":"P4","bottom":"P5","round":1},{"id":"J9","top":"P6","bottom":"V:J2","round":2},{"id":"J10","top":"V:J3","bottom":"P11","round":2},{"id":"J11","top":"P12","bottom":"V:J4","round":2},{"id":"J12","top":"P15","bottom":"P16","round":1},{"id":"J13","top":"P17","bottom":"V:J5","round":2},{"id":"J14","top":"V:J6","bottom":"P22","round":2},{"id":"J15","top":"V:J7","bottom":"V:J8","round":3},{"id":"J16","top":"V:J9","bottom":"V:J10","round":3},{"id":"J17","top":"V:J11","bottom":"V:J12","round":3},{"id":"J18","top":"V:J13","bottom":"V:J14","round":3},{"id":"J19","top":"V:J15","bottom":"V:J16","round":4},{"id":"J20","top":"V:J17","bottom":"V:J18","round":4},{"id":"J21","top":"L:J19","bottom":"L:J20","round":5},{"id":"J22","top":"P22","bottom":"P2","round":1}],"final":"J19","thirdPlace":"J21"}'::jsonb) ON CONFLICT (numero_inscrito) DO UPDATE SET matches_graph = EXCLUDED.matches_graph;

-- N=23: PENDING (visual parser not yet implemented; will add in task 3)

-- N=24: PENDING (visual parser not yet implemented; will add in task 3)

-- N=25: PENDING (visual parser not yet implemented; will add in task 3)

-- N=26: PENDING (visual parser not yet implemented; will add in task 3)

-- N=27: PENDING (visual parser not yet implemented; will add in task 3)

-- N=28: PENDING (visual parser not yet implemented; will add in task 3)

-- N=29: PENDING (visual parser not yet implemented; will add in task 3)

-- N=30: PENDING (visual parser not yet implemented; will add in task 3)

-- N=31: PENDING (visual parser not yet implemented; will add in task 3)

-- N=32: PENDING (visual parser not yet implemented; will add in task 3)

-- N=33: PENDING (visual parser not yet implemented; will add in task 3)

-- N=34: PENDING (visual parser not yet implemented; will add in task 3)

-- N=35: PENDING (visual parser not yet implemented; will add in task 3)

-- N=36: PENDING (visual parser not yet implemented; will add in task 3)

-- N=37: PENDING (visual parser not yet implemented; will add in task 3)

-- N=38: PENDING (visual parser not yet implemented; will add in task 3)

-- N=39: PENDING (visual parser not yet implemented; will add in task 3)

-- N=40: PENDING (visual parser not yet implemented; will add in task 3)

-- N=41: PENDING (visual parser not yet implemented; will add in task 3)

-- N=42: PENDING (visual parser not yet implemented; will add in task 3)

-- N=43: PENDING (visual parser not yet implemented; will add in task 3)

-- N=44: PENDING (visual parser not yet implemented; will add in task 3)

-- N=45: PENDING (visual parser not yet implemented; will add in task 3)

-- N=46: PENDING (visual parser not yet implemented; will add in task 3)

-- N=47: PENDING (visual parser not yet implemented; will add in task 3)

-- N=48: PENDING (visual parser not yet implemented; will add in task 3)

-- N=49: PENDING (visual parser not yet implemented; will add in task 3)

-- N=50: PENDING (visual parser not yet implemented; will add in task 3)

-- N=51: PENDING (visual parser not yet implemented; will add in task 3)

-- N=52: PENDING (visual parser not yet implemented; will add in task 3)

-- N=53: PENDING (visual parser not yet implemented; will add in task 3)

-- N=54: PENDING (visual parser not yet implemented; will add in task 3)

-- N=55: PENDING (visual parser not yet implemented; will add in task 3)

-- N=56: PENDING (visual parser not yet implemented; will add in task 3)

-- N=57: PENDING (visual parser not yet implemented; will add in task 3)

-- N=58: PENDING (visual parser not yet implemented; will add in task 3)

-- N=59: PENDING (visual parser not yet implemented; will add in task 3)

-- N=60: PENDING (visual parser not yet implemented; will add in task 3)

-- N=61: PENDING (visual parser not yet implemented; will add in task 3)

-- N=62: PENDING (visual parser not yet implemented; will add in task 3)

-- N=63: PENDING (visual parser not yet implemented; will add in task 3)

-- N=64: PENDING (visual parser not yet implemented; will add in task 3)

-- N=65: PENDING (visual parser not yet implemented; will add in task 3)

-- N=66: PENDING (visual parser not yet implemented; will add in task 3)

-- N=67: PENDING (visual parser not yet implemented; will add in task 3)

-- N=68: PENDING (visual parser not yet implemented; will add in task 3)

-- N=69: PENDING (visual parser not yet implemented; will add in task 3)

-- N=70: PENDING (visual parser not yet implemented; will add in task 3)

-- N=71: PENDING (visual parser not yet implemented; will add in task 3)

-- N=72: PENDING (visual parser not yet implemented; will add in task 3)

-- N=73: PENDING (visual parser not yet implemented; will add in task 3)

-- N=74: PENDING (visual parser not yet implemented; will add in task 3)

-- N=75: PENDING (visual parser not yet implemented; will add in task 3)

-- N=76: PENDING (visual parser not yet implemented; will add in task 3)

-- N=77: PENDING (visual parser not yet implemented; will add in task 3)
