-- Auto-generated by backend/scripts/extract-bracket-byes.py
-- DO NOT EDIT MANUALLY. To regenerate: cd backend && python scripts/extract-bracket-byes.py

-- N=2: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (2, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=3: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (3, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=4: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (4, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=5: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (5, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=6: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (6, '{1,6}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=7: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (7, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=8: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (8, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=9: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (9, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=10: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (10, '{1,10}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=11: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (11, '{1,6,11}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=12: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (12, '{1,6,7,12}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=13: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (13, '{1,6,13}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=14: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (14, '{1,14}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=15: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (15, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=16: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (16, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=17: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (17, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=18: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (18, '{1,18}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=19: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (19, '{1,10,19}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=20: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (20, '{1,10,11,20}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=21: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (21, '{1,10,11,16,21}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=22: EXPLICIT (planilha tem tabela isbye)
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (22, '{1,6,11,12,17,22}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=23: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (23, '{1,5,6,11,12,18,23}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=24: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (24, '{1,6,7,12,13,18,19,24}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=25: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (25, '{1,6,7,12,13,19,25}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=26: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (26, '{1,6,7,13,14,26}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=27: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (27, '{1,7,13,14,27}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=28: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (28, '{1,14,15,28}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=29: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (29, '{1,15,29}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=30: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (30, '{1,30}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=31: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (31, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=32: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (32, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=33: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (33, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=34: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (34, '{1,34}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=35: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (35, '{1,18,35}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=36: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (36, '{1,18,19,36}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=37: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (37, '{1,10,18,19,37}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=38: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (38, '{1,9,10,19,20,38}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=39: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (39, '{1,9,10,19,20,30,39}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=40: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (40, '{1,10,11,20,21,30,31,40}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=41: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (41, '{1,10,11,20,21,30,31,41}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=42: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (42, '{1,10,11,21,22,31,32,42}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=43: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (43, '{1,10,11,21,22,32,33,43}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=44: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (44, '{1,11,12,22,23,33,34,44}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=45: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (45, '{1,11,12,22,23,33,34,45}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=46: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (46, '{1,11,12,23,24,34,35,46}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=47: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (47, '{1,11,12,23,24,35,36,47}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=48: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (48, '{1,12,13,24,25,36,37,48}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=49: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (49, '{1,12,13,24,25,36,37,49}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=50: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (50, '{1,12,13,25,26,37,38,50}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=51: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (51, '{1,12,13,25,26,38,39,51}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=52: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (52, '{1,13,14,26,27,39,40,52}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=53: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (53, '{1,13,14,26,27,39,40,53}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=54: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (54, '{1,13,14,27,28,40,41,54}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=55: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (55, '{1,13,14,27,28,41,42,55}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=56: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (56, '{1,14,15,28,29,42,43,56}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=57: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (57, '{1,14,15,28,29,43,57}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=58: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (58, '{1,14,15,29,30,58}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=59: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (59, '{1,15,29,30,59}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=60: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (60, '{1,30,31,60}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=61: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (61, '{1,31,61}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=62: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (62, '{1,62}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=63: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (63, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=64: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (64, '{}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=65: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (65, '{1}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=66: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (66, '{1,66}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=67: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (67, '{1,34,67}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=68: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (68, '{1,34,35,68}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=69: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (69, '{1,18,34,35,69}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=70: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (70, '{1,17,18,35,36,70}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=71: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (71, '{1,17,18,35,36,54,71}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=72: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (72, '{1,18,19,36,37,54,55,72}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=73: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (73, '{1,18,19,36,37,54,55,73}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=74: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (74, '{1,18,19,37,38,55,56,74}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=75: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (75, '{1,18,19,37,38,56,57,75}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=76: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (76, '{1,19,20,38,39,57,58,76}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;

-- N=77: DERIVED (formula min(N-pot2_below, pot2_above-N) + standard seeding) -- VERIFICAR
INSERT INTO bracket_chaves_byes (numero_inscrito, posicoes_bye) VALUES (77, '{1,19,20,38,39,57,58,77}') ON CONFLICT (numero_inscrito) DO UPDATE SET posicoes_bye = EXCLUDED.posicoes_bye;
