export {
  LayoutDashboard as Panel,
  Trophy,
  Users as Cadastro,
  Brackets as Bracket,
  Group as Groups,
  ListOrdered as Order,
  Calendar as Evento,
  FileText as Report,
  Settings,
  ShieldCheck as Admin,
  ChevronRight as ChevR,
  ChevronDown,
  PanelLeftClose as Collapse,
  Search,
  Bell,
  Sun,
  Moon,
  Lock,
  Check,
  ArrowRight,
  Maximize,
  Minimize,
  Save,
  Pin,
  Construction,
  Plus,
  X,
  Dices as Dice,
  Shuffle,
  Crown,
} from 'lucide-react'
